Repository eleven-labs/github, pull requests merged in 2020-02, with the labels that each got.

#28 feat(user,team): add thibaut algrin
  teams.tf
  users.tf
Labels: status/mergeable, type/feat

#29 feat(user,team): add michael benaim
  teams.tf
  users.tf
Labels: status/mergeable, type/feat

#30 feat(user,team): add thomas bethmont
  teams.tf
  users.tf
Labels: status/mergeable, type/feat

#31 feat(user,team,repo): update thomas pejout permissions
  repositories.tf
  teams.tf
  users.tf
Labels: status/reviewable, type/feat

#32 refactor(team): rename team-roles variable to team-members_role
  module/team/main.tf
  module/team/variables.tf
  teams.tf
Labels: status/mergeable, type/refactor

#33 refactor(repository): module outputs naming
  module/repository/outputs.tf
Labels: status/mergeable, type/refactor

#34 feat(team): team repository permissions
  module/repository/outputs.tf
  module/team/main.tf
  module/team/variables.tf
  teams.tf
Labels: status/mergeable, type/feat

#35 chore(repository): remove useless config
  repositories.tf
Labels: status/reviewable, type/chore

#22 chore(oss): readme
  README.md
Labels: status/mergeable, type/chore

#36 feat(user,team) : add sophie kontomarkos
  teams.tf
  users.tf
Labels: status/reviewable
